remote_theme: pages-themes/time-machine@v0.2.0
plugins: 
- jekyll-remote-theme 
# theme: jeykll-theme-Modernist 
title: ECE 4160 - Fast Robots (pgj23)
description: Submission page for ECE 4160-Fast Robots. Author: Paul Judge (pgj23)
